export const IMAGES = {
  MPL: "/images/MPL.jpg",
  MPL2: "/images/MPL2.jpg",
  MPLJerseyRelease: "/images/MPLJerseyRelease.jpg",
  MPLJerseyRelease2: "/images/MPLJerseyRelease2.jpg",
  MPLPoster: "/images/MPLPoster.jpg",
  MycRunners: "/images/MycRunners.jpg",
  PosterLaunch: "/images/PosterLaunch.jpg",
  PosterLaunch3: "/images/PosterLaunch3.jpg",
  PosterLaunch4: "/images/PosterLaunch4.jpg",
  PosterRelease: "/images/PosterRelease.jpg",
  VolleyWinners: "/images/VolleyWinners.jpg",
  Cleaning : "/images/Cleaning.jpg",
  Cleaning2 : "/images/Cleaning2.jpg",
  Cleaning3 : "/images/Cleaning3.jpg",
  DasaraFlex : "/images/DasaraFlex.jpg",
  DasaraFlexfull : "/images/DasaraFlexfull.jpg",
  FlagHoist : "/images/FlagHoist.jpg",
  FlagHoist2 : "/images/FlagHoist2.jpg",
  FlagHoist3 : "/images/FlagHoist3.jpg",
  FlagHoist4 : "/images/FlagHoist4.jpg",
  FlagHoistMain : "/images/FlagHoistMain.jpg",
  Guest : "/images/Guest.jpg",
  Guest2 : "/images/Guest2.jpg",
  Guest3 : "/images/Guest3.jpg",
  HoreKanike : "/images/HoreKanike.jpg",
  Horekanike2 : "/images/Horekanike2.jpg",
  KesardGammath : "/images/KesardGammath.jpg",
  KesardOnjidina : "/images/KesardOnjidina.jpg",
  CricketAunction:"/images/CricketAunction.png",
  CricketMatch:"/images/CricketMatch2026.png",
  VolleyBallMAtch:"/images/VolleyBallMAtch.png",
  VolleyballAunction:"/images/VolleyballAunction.png",
  Mardoli1:"/images/Mardoli1.png",
  Mardoli2:"/images/Mardoli2.png",
  MYC_Logo: "/images/MYC_Logo.jpg",
  Charan:"/MembersImages/Charan.png",
  Paandu:"/MembersImages/Paandu.png",
  Karthik:"/MembersImages/Karthik.jpg",
  Yathin_Kulal:"/MembersImages/Yathin_Kulal.png",
  ShushankPoojary:"/MembersImages/ShushankPoojary.jpg",
  Sunil:"/MembersImages/Sunil.jpg",
  Akhil:"/MembersImages/Akhil.png",
  Sathya:"/MembersImages/Sathya.jpg",
  Mahesh:"/MembersImages/Mahesh.jpg",
  Anil:"/MembersImages/Anil.jpg",
  Putta:"/MembersImages/Putta.jpg",
  Achal:"/MembersImages/Achal.jpg",
  Sanvith:"/MembersImages/Sanvith.jpg",
  Adithya:"/MembersImages/Adithya.jpg",
  Saish:"/MembersImages/Saish.png",
  Veeraj:"/MembersImages/Veeraj.jpg",
  Prathap:"/MembersImages/Prathap.jpg",
  Dinesh:"/MembersImages/Dinesh.jpg",
  Hari:"/MembersImages/Hari.jpg",
  Gauthu:"/MembersImages/Gauthu.jpg",
  Varshith:"/MembersImages/Varshith.jpg",
  Nirmith:"/MembersImages/Nirmith.jpg",
  Harish:"/MembersImages/Harish.jpg",
  Jitesh:"/MembersImages/Jitesh.png",
  MohanK:"/MembersImages/Mohank.png",
  Pramith:"/MembersImages/Pramith.png",
  Shivu:"/MembersImages/Shivu.png",
  Yahtin:"/MembersImages/Yathin.png",
  Kishore:"/MembersImages/Kishore.png",
  NO:"/MembersImages/NoPerson.png",
  Nithin:"/MembersImages/Nithin.jpg",
  Jiteshp:"/MembersImages/Jiteesh.jpg",
  Deepak:"/MembersImages/Deepak.jpg",
  Santhu:"/MembersImages/Santhu.jpg",
  Manoj:"/MembersImages/Manoj.jpg",
  Mohankulal:"/MembersImages/Mohan.jpg",
  Bhoosu:"/MembersImages/Bhoosu.jpg",
  Sudheer:"/MembersImages/Sudheer.jpg",
  Ashok:"/MembersImages/Ashok.jpg",
  Pradeep:"/MembersImages/Pradeep.jpg",
  Jaya:"/MembersImages/Jaya.jpg",
  Harishk:"/MembersImages/Harishk.jpg",
} as const;
